import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "@/Providers/SessionProvider";
import ReduxProvider from "@/Providers/ReduxProvider";
import { ThemeProvider } from "@/Providers/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
 title: "HRM Project",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <body className={inter.className}>
    <NextAuthSessionProvider>
     <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
     >
      {children}
      <Toaster />
     </ThemeProvider>
    </NextAuthSessionProvider>
   </body>
  </html>
 );
}
